name: Deploy Node App
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "MONGO=${{secrets.MONGO}}" >> .env && echo "JWT_SECRET=${{secrets.JWT_SECRET}}" >> .env && echo "DOCKERHUB_USERNAME=${{secrets.DOCKERHUB_USERNAME}}" >> .env && echo "DOCKERHUB_TOKEN=${{secrets.DOCKERHUB_TOKEN}}" >> .env && echo "CLOUDINARY_SECRET=${{secrets.CLOUDINARY_SECRET}}" >> .env $$ each "CLOUDINARY_NAME=${{secrets.CLOUDINARY_NAME}}" >> .env && echo "CLOUDINARY_API=${{secrets.CLOUDINARY_API}}" >> .env
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build  Docker img
        run: docker build -t changwhioh/chatwithfunction .
      - name: Publish this image to docker hub
        run: docker push changwhioh/chatwithfunction:latest

  Deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: echo "Deploying..."
      - name: Pull image from docker hub
        run: docker pull changwhioh/chatwithfunction:latest
      - name: Delete old container
        run: docker rm -f chatwithfunction
      - name: Run Docker Container
        run: docker run  -d -p 3000:3000 --name chatwithfunction changwhioh/chatwithfunction